#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Run blockMesh
blockMesh

# Print cell stats
rm -f log.checkMesh
runApplication checkMesh

# Run topoSet and Split regions
splitMeshRegions -cellZones -overwrite

# Run setFields
cp ./0/air/S.org ./0/air/S
cp ./system/setFieldsDict ./system/air/
setFields -region air

# Output message
echo
echo Case created



#------------------------------------------------------------------------------
