#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

python bolsig/clean.py
python bolsig/run.py

cp bolsig/bolsigOutput/bolsigProperties constant/

#------------------------------------------------------------------------------
