#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Delete cellToRegion file
rm -f ./constant/cellToRegion

# Delete all subdirectories into the system and constant directories
find ./system/*   -type d 2>/dev/null -exec rm -v -r {} \;
find ./constant/* -type d 2>/dev/null -exec rm -v -r {} \;

# Delete all time steps and logs
rm -f log.*
cleanCase

# Output message
echo
echo Cleaning Completed

#------------------------------------------------------------------------------
