#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./streamer/Allrun

./chargeTransport/Allrun

./flow/Allrun



#------------------------------------------------------------------------------
