#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Get the solver name from the controlDict file
application=$(getApplication)

# Run solver
$application


#------------------------------------------------------------------------------
