#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Rename directory
startTime=1e-05
cp -R 0 $startTime
foamDictionary -entry "startTime" -set "$startTime" system/controlDict

# Copy geometry and mesh from streamer case
cp -R ../streamer/constant/polyMesh ../streamer/constant/dielectric ../streamer/constant/insulator constant/

# Run mapFields
mapFieldsPar ../streamer -mapMethod direct -consistent -sourceTime latestTime
mapFieldsPar ../streamer -mapMethod direct -sourceRegion dielectric -consistent -sourceTime latestTime -targetRegion dielectric
mapFieldsPar ../streamer -mapMethod direct -sourceRegion insulator  -consistent -sourceTime latestTime -targetRegion insulator

# Output message
echo
echo Case created.



#------------------------------------------------------------------------------
