#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltI/volt/g' ./{}/voltI {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltD/volt/g' ./{}/dielectric/voltD {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EI/E/g' ./{}/EI {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/ED/E/g' ./{}/dielectric/ED {} \;
#------------------------------------------------------------------------------
