#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean
./Allmesh
./runParallel
reconstructPar -allRegions -latestTime
rm -r processor*

#------------------------------------------------------------------------------
