#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltA/volt/g' ./{}/voltA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltD/volt/g' ./{}/dielectric/voltD {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltE/volt/g' ./{}/encapsulator/voltE {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltAextMag/voltExtMag/g' ./{}/voltAextMag {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltDextMag/voltExtMag/g' ./{}/dielectric/voltDextMag {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltEextMag/voltExtMag/g' ./{}/encapsulator/voltEextMag {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltArho/voltRho/g' ./{}/voltArho {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltDrho/voltRho/g' ./{}/dielectric/voltDrho {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltErho/voltRho/g' ./{}/encapsulator/voltErho {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EA/E/g' ./{}/EA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/ED/E/g' ./{}/dielectric/ED {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EE/E/g' ./{}/encapsulator/EE {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EAextMag/EextMag/g' ./{}/EAextMag {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EDextMag/EextMag/g' ./{}/dielectric/EDextMag {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EEextMag/EextMag/g' ./{}/encapsulator/EEextMag {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EArho/Erho/g' ./{}/EArho {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EDrho/Erho/g' ./{}/dielectric/EDrho {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EErho/Erho/g' ./{}/encapsulator/EErho {} \;
#------------------------------------------------------------------------------
