#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get the solver name from the controlDict file
application=$(getApplication)

# Replace 0 directory contents with 0.org
rm -v -r 0
cp -r 0.org 0

# Copy fvSchemes and fvSolution into Zone folders
find ./system/* -type d 2>/dev/null -exec cp -v ./system/fvSchemes {} \;
find ./system/* -type d 2>/dev/null -exec cp -v ./system/fvSolution {} \;

# Run solver
$(getApplication)


#------------------------------------------------------------------------------
