#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Delete cellToRegion file
rm -f ./constant/cellToRegion

# Delete all subdirectories into the system and constant directories
find ./system/*   -type d 2>/dev/null -exec rm -v -r {} \;
find ./constant/* -type d 2>/dev/null -exec rm -v -r {} \;

# Reset fields
rm -f ./0/voltR
mv ./0/voltR.org ./0/voltR
rm -f ./0/rhoq
mv ./0/rhoq.org ./0/rhoq

# Delete all time steps and logs
rm -f log.*
rm -f ./0/cellToRegion
find ./0/* -type d 2>/dev/null -exec rm -r {}/cellToRegion \;
cleanCase

# Output message
echo
echo Cleaning Completed

#------------------------------------------------------------------------------
