#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltA/volt/g' ./{}/voltA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltD/volt/g' ./{}/dielectric/voltD {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltΙ/volt/g' ./{}/insulator/voltI {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EA/E/g' ./{}/EA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/ED/E/g' ./{}/dielectric/ED {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EI/E/g' ./{}/insulator/EI {} \;
#------------------------------------------------------------------------------
