#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./1_discharge/Allrun

./2_ionicMotion/Allrun

./3_flow/Allrun



#------------------------------------------------------------------------------
