#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# MapFields
mapFields ../charge -consistent -sourceTime "latestTime"

# Get the solver name from the controlDict file
application=$(getApplication)

# Run solver
$(getApplication)


#------------------------------------------------------------------------------
