#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy geometry and mesh from streamer case
cp -R ../1_discharge/constant/polyMesh constant/

# TopoSet for kinetic energy injection
topoSet
# Output message
echo
echo Case created.



#------------------------------------------------------------------------------
