#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Delete 0 folder
rm -r 0

# Run blockMesh
blockMesh

# Refine mesh
for index in {1..1}
do
    topoSet -dict system/topoSetDictRegion$index
    refineMesh -dict system/refineMeshDictRegion -overwrite 
done

# Split dielectric regions
splitMeshRegions -cellZones -overwrite
rm -r ./system/region0/

# Replace 0 directory contents with 0.org
rm -r 0
cp -r 0.org 0

# Output message
echo
echo Case created.

#------------------------------------------------------------------------------
