#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltA/volt/g' ./{}/voltA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltD/volt/g' ./{}/dielectric/voltD {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/voltD2/volt/g' ./{}/dielectric2/voltD2 {} \;

find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/EA/E/g' ./{}/EA {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/ED/E/g' ./{}/dielectric/ED {} \;
find ./[0-9]* -type d 2>/dev/null -exec sed -i 's/ED2/E/g' ./{}/dielectric2/ED2 {} \;
#------------------------------------------------------------------------------
