#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Delete all time steps
cleanCase

# Output message
echo
echo Cleaning Completed

#------------------------------------------------------------------------------
