#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions          # Tutorial clean functions
#------------------------------------------------------------------------------

# Delete cellToRegion file
rm -rf constant/cellToRegion

# Delete all subdirectories into the system and constant directories
rm -rf constant/*/polyMesh  # region meshes
rm -rf system/*/

# Reset fields if there is a 0.org directory
if [ -d ./0.org ]; then 
    rm -v -r 0 ;
    mv -v 0.org 0 ; 
fi

# Delete all time steps and logs
rm -f log.*
rm -f 0/cellToRegion
rm -rf system/*/
rm -rf 0/*/cellToRegion
cleanCase

# Output message
echo
echo Cleaning Completed

#------------------------------------------------------------------------------

