#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# # Get the solver name from the controlDict file
application=$(getApplication)
nProcs=$(getNumberOfProcessors)

# Copy fvSchemes, fvSolution and decomposeParDict into Zone folders
# find ./system/* -type d 2>/dev/null -exec cp -v ./system/fvSchemes {} \;
# find ./system/* -type d 2>/dev/null -exec cp -v ./system/fvSolution {} \;
# find ./system/* -type d 2>/dev/null -exec cp -v ./system/decomposeParDict {} \;

# MapFields
# mapFields ../elstatic -consistent

# Decompose
decomposePar -allRegions -force

# # Copy polyMesh from constant into all processor directories
# for ((i = 0 ; i < $nProcs ; i++))
# do
#     cp -avr ./constant/polyMesh ./processor$i/constant
# done

# Run solver
mpirun -np $nProcs $(getApplication) -parallel


#------------------------------------------------------------------------------
