#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

mapFieldsPar ../flow_2D_laminar -mapMethod direct -consistent -sourceTime latestTime -fields '(He N2 O2)'

# Output message
echo
echo Case mapped.

#------------------------------------------------------------------------------
