#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Rename directory
startTime=5e-05
cp -R 0 $startTime
foamDictionary -entry "startTime" -set "$startTime" system/controlDict

# Copy geometry and mesh from streamer case
cp -R ../1_discharge/constant/polyMesh ../1_discharge/constant/dielectric ../1_discharge/constant/encapsulator constant/

# Run mapFields
mapFieldsPar ../1_discharge -mapMethod direct -consistent -sourceTime latestTime
mapFieldsPar ../1_discharge -mapMethod direct -sourceRegion dielectric -consistent -sourceTime latestTime -targetRegion dielectric
mapFieldsPar ../1_discharge -mapMethod direct -sourceRegion encapsulator  -consistent -sourceTime latestTime -targetRegion encapsulator

# Output message
echo
echo Case created.



#------------------------------------------------------------------------------
