#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

echo ========================================
echo Compile OpenFOAM libraries
echo ========================================

#------------------------------------------------------------------------------

wmake libso parabolicInlet
wmake libso potentialTools
wmake libso transportTools
wmake libso plasmaChemistryTools

#------------------------------------------------------------------------------

echo ========================================
echo Done compiling OpenFOAM libraries
echo ========================================

#------------------------------------------------------------------------------
