#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Create mesh
# gmsh system/reactor.geo -3 -o system/reactor.msh -format msh2
# gmshToFoam system/reactor.msh 
# changeDictionary
blockMesh

# Replace 0 directory contents with 0.org
rm -fr 0
cp -r 0.org 0

# Output message
echo
echo Case created.

#------------------------------------------------------------------------------
