#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Replace 0 directory contents with 0.org
rm -fr 0
cp -r 0.org 0

# Run solver
$(getApplication)

#------------------------------------------------------------------------------
